services:
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    user: root
    ports:
      - "12345:12345"
    volumes:
      - "./config/config.alloy:/etc/alloy/config.alloy"
      - "./config/endpoints.json:/etc/alloy/endpoints.json"
      - "/var/log:/var/log/host"
    command: [
      "run",
      "--server.http.listen-addr=0.0.0.0:12345",
      "--stability.level=public-preview",
      "/etc/alloy/config.alloy"
    ]